// UI action types
export const SIDENAV_TOGGLED           = 'SIDENAV_TOGGLED';
export const DETAILBAR_OPENED          = 'DETAILBAR_OPENED';
export const DETAILBAR_CLOSED          = 'DETAILBAR_CLOSED';
export const DETAILNAV_TOGGLED         = 'DETAILNAV_TOGGLED';
export const DETAILNAV_UPDATE_CONTENT  = 'DETAILNAV_UPDATE_CONTENT';

// API action types
export const FETCH_SUBJECTS            = 'FETCH_SUBJECTS';
export const FETCH_SUBJECTS_FULFILLED  = 'FETCH_SUBJECTS_FULFILLED';
export const FETCH_SUBJECTS_REJECTED   = 'FETCH_SUBJECTS_REJECTED';
export const FETCH_SUBJECT             = 'FETCH_SUBJECT';
export const FETCH_SUBJECT_FULFILLED   = 'FETCH_SUBJECT_FULFILLED';
export const FETCH_SUBJECT_REJECTED    = 'FETCH_SUBJECT_REJECTED';
export const ADD_SUBJECT               = 'ADD_SUBJECT';
export const ADD_SUBJECT_FULFILLED     = 'ADD_SUBJECT_FULFILLED';
export const ADD_SUBJECT_REJECTED      = 'ADD_SUBJECT_REJECTED';
export const UPDATE_SUBJECT            = 'UPDATE_SUBJECT';
export const UPDATE_SUBJECT_FULFILLED  = 'UPDATE_SUBJECT_FULFILLED';
export const UPDATE_SUBJECT_REJECTED   = 'UPDATE_SUBJECT_REJECTED';
export const DELETE_SUBJECT            = 'DELETE_SUBJECT';
export const DELETE_SUBJECT_FULFILLED  = 'DELETE_SUBJECT_FULFILLED';
export const DELETE_SUBJECT_REJECTED   = 'DELETE_SUBJECT_REJECTED';

export const FETCH_BLOCKING_STATS = 'FETCH_BLOCKING_STATS';
export const FETCH_BLOCKING_STATS_FULFILLED  = 'FETCH_BLOCKING_STATS_FULFILLED';
export const FETCH_BLOCKING_STATS_REJECTED   = 'FETCH_BLOCKING_STATS_REJECTED';
export const FETCH_BLOCKING_STATS_DATA = 'FETCH_BLOCKING_STATS_DATA';
export const FETCH_BLOCKING_STATS_DATA_FULFILLED = 'FETCH_BLOCKING_STATS_DATA_FULFILLED';
export const FETCH_BLOCKING_STATS_DATA_REJECTED = 'FETCH_BLOCKING_STATS_DATA_REJECTED';

export const FETCH_SIM_MEASURE_STATS = 'FETCH_SIM_MEASURE_STATS';
export const FETCH_SIM_MEASURE_STATS_FULFILLED = 'FETCH_SIM_MEASURE_STATS_FULFILLED';
export const FETCH_SIM_MEASURE_STATS_REJECTED = 'FETCH_SIM_MEASURE_STATS_REJECTED';
export const FETCH_SIM_MEASURE_STATS_DATA = 'FETCH_SIM_MEASURE_STATS_DATA';
export const FETCH_SIM_MEASURE_STATS_DATA_FULFILLED = 'FETCH_SIM_MEASURE_STATS_DATA_FULFILLED';
export const FETCH_SIM_MEASURE_STATS_DATA_REJECTED = 'FETCH_SIM_MEASURE_STATS_DATA_REJECTED';

export const FETCH_CLASSIFIER_STATS = 'FETCH_CLASSIFIER_STATS';
export const FETCH_CLASSIFIER_STATS_FULFILLED = 'FETCH_CLASSIFIER_STATS_FULFILLED';
export const FETCH_CLASSIFIER_STATS_REJECTED = 'FETCH_CLASSIFIER_STATS_REJECTED';
export const FETCH_CLASSIFIER_STATS_DATA = 'FETCH_CLASSIFIER_STATS_DATA';
export const FETCH_CLASSIFIER_STATS_DATA_FULFILLED = 'FETCH_CLASSIFIER_STATS_DATA_FULFILLED';
export const FETCH_CLASSIFIER_STATS_DATA_REJECTED = 'FETCH_CLASSIFIER_STATS_DATA_REJECTED';
