// UI action types
export const SIDENAV_TOGGLED          = 'SIDENAV_TOGGLED';

// API action types
export const FETCH_SUBJECTS           = 'FETCH_SUBJECTS';
export const FETCH_SUBJECTS_FULFILLED = 'FETCH_SUBJECTS_FULFILLED';
export const FETCH_SUBJECTS_REJECTED  = 'FETCH_SUBJECTS_REJECTED';
export const ADD_SUBJECT              = 'ADD_SUBJECT';
export const ADD_SUBJECT_FULFILLED    = 'ADD_SUBJECT_FULFILLED';
export const ADD_SUBJECT_REJECTED     = 'ADD_SUBJECT_REJECTED';
export const UPDATE_SUBJECT           = 'UPDATE_SUBJECT';
export const UPDATE_SUBJECT_FULFILLED = 'UPDATE_SUBJECT_FULFILLED';
export const UPDATE_SUBJECT_REJECTED  = 'UPDATE_SUBJECT_REJECTED';
export const DELETE_SUBJECT           = 'DELETE_SUBJECT';
export const DELETE_SUBJECT_FULFILLED = 'DELETE_SUBJECT_FULFILLED';
export const DELETE_SUBJECT_REJECTED  = 'DELETE_SUBJECT_REJECTED';
