import 'react';
import 'axios';
import 'classnames';
import 'material-ui';
import 'redux';
import 'redux-thunk';
import 'react-tap-event-plugin';
import 'redux-logger';
import 'redux-promise-middleware';
import 'react-redux';
import 'react-dom';
import {Router, Link, IndexLink, IndexRoute, Redirect, Route, hashHistory} from 'react-router';
